project:
  type: website

website:
  title: "Prueba"
  reader-mode: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Extras"
        menu:
          - text: "Información"
            href: about.qmd
          - compatibility.qmd
      - text: "Tutoriales"
        href: tutorials/tutorial.qmd
  
  sidebar:
    - title: "Tutoriales"
      style: "docked"
      background: light
      contents:
        - tutorials/tutorial.qmd
        - text: "---"
        - section: "Jupyter"
          contents:
            - tutorials/tutorial1.qmd
            - tutorials/tutorial2.qmd
            - text: "Ejemplo QMD"
              href: ejercicios/hello.qmd
            - text: "Ejemplo .ipynb"
              href: ejercicios/hello2.ipynb

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



